site_name: Usacloudドキュメント
site_url: https://sacloud.github.io/usacloud/
site_description: Usacloud日本語ドキュメント
site_author: '@sacloud-authors'
repo_url: https://github.com/sacloud/usacloud
repo_name: usacloud
copyright: Copyright (C) 2017-2022 The Usacloud Authors.
theme:
    name: material
    language: ja
    features:
        - navigation.tabs
extra:
    analytics:
        provider: google
        property: G-9JFNZ70H7B
extra_css:
  - css/extra.css
markdown_extensions:
    - admonition
    - attr_list
    - pymdownx.highlight
    - pymdownx.superfences
nav:
  - ホーム: index.md
  - 利用方法/ガイド:
      - インストール:
          - installation/start_guide.md
      - 利用方法/ガイド:
          - 基本的な使い方: guides/basic_usage.md
          - クエリ/出力の加工: guides/query.md
          - completionコマンド: guides/completion.md
          - restコマンド: guides/rest.md
      - アップグレード:
            - v1.0へのアップグレード: upgrade/v1_0_0.md
            - v1.1へのアップグレード: upgrade/v1_1_0.md
  - リファレンス:
      - オプション/設定:
          - グローバルオプション: references/global.md
          - プロファイル: references/profile.md
          - 環境変数: references/env.md
      - コマンド:
          - プロファイル/コンフィグ:
              - config: references/config.md
          - 認証情報:
              - auth-status: references/auth-status.md
          - コンピューティング:
              - private-host: references/private-host.md
              - server: references/server.md
          - ストレージ:
              - archive: references/archive.md
              - auto-backup: references/auto-backup.md
              - cdrom: references/cdrom.md
              - disk: references/disk.md
          - ネットワーキング:
              - bridge: references/bridge.md
              - internet: references/internet.md
              - local-router: references/local-router.md
              - packet-filter: references/packet-filter.md
              - switch: references/switch.md
          - ネットワーク関連サブリソース:
              - interface: references/interface.md
              - ipaddress: references/ipaddress.md
              - ipv6addr: references/ipv6addr.md
              - ipv6net: references/ipv6net.md
              - subnet: references/subnet.md
          - アプライアンス:
              - database: references/database.md
              - load-balancer: references/load-balancer.md
              - nfs: references/nfs.md
              - vpc-router: references/vpc-router.md
          - セキュアモバイル:
                - mobile-gateway: references/mobile-gateway.md
                - sim: references/sim.md
          - 共通サービスアイテム:
              - dns: references/dns.md
              - gslb: references/gslb.md
              - proxy-lb: references/proxy-lb.md
              - simple-monitor: references/simple-monitor.md
          - 請求関連:
              - bill: references/bill.md
              - coupon: references/coupon.md
          - Labプロダクト:
              - certificate-authority: references/certificate-authority.md
              - enhanced-db: references/enhanced-db.md
              - container-registry: references/container-registry.md
              - esme: references/esme.md
          - ウェブアクセラレータ:
              - web-accelerator: references/web-accelerator.md
          - その他サービス:
              - icon: references/icon.md
              - license: references/license.md
              - note: references/note.md
              - ssh-key: references/ssh-key.md
          - リージョン/ゾーン情報参照:
              - region: references/region.md
              - zone: references/zone.md
          - サービス/プロダクト情報参照:
              - disk-plan: references/disk-plan.md
              - internet-plan: references/internet-plan.md
              - license-info: references/license-info.md
              - private-host-plan: references/private-host-plan.md
              - server-plan: references/server-plan.md
              - service-class: references/service-class.md
          - その他:
              - completion: references/completion.md
              - rest: references/rest.md
              - self: references/self.md
              - update-self: references/update-self.md
