site_name: Terraform for さくらのクラウド(v2)
site_url: https://docs.usacloud.jp/terraform
site_description: Terrform for さくらのクラウド(v2)
site_author: '@yamamoto-febc'
repo_url: https://github.com/sacloud/terraform-provider-sakuracloud
repo_name: terraform-provider-sakuracloud
copyright: Copyright (C) 2016-2021 terraform-provider-sakuracloud authors
theme:
  name: material
  language: ja
  features:
    - navigation.tabs
extra:
  analytics:
    provider: google
    property: UA-63739336-5
extra_css:
  - css/extra.css
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
nav:
  - ホーム: index.md
  - ガイド:
    - アップグレードガイド:
      - v2.16での変更点: guides/upgrade_to_v2.16.0.md
      - v2.15での変更点: guides/upgrade_to_v2.15.0.md
      - v2.14での変更点: guides/upgrade_to_v2.14.0.md
      - v2.13での変更点: guides/upgrade_to_v2.13.0.md
      - v2.12での変更点: guides/upgrade_to_v2.12.0.md
      - v2.11での変更点: guides/upgrade_to_v2.11.0.md
      - v2.10での変更点: guides/upgrade_to_v2.10.0.md
      - v2.9での変更点: guides/upgrade_to_v2.9.0.md
      - v2.8での変更点: guides/upgrade_to_v2.8.0.md
      - v2.7での変更点: guides/upgrade_to_v2.7.0.md
      - v2.6での変更点: guides/upgrade_to_v2.6.0.md
      - v2.5での変更点: guides/upgrade_to_v2.5.0.md
      - v2.4での変更点: guides/upgrade_to_v2.4.0.md
      - v2.3での変更点: guides/upgrade_to_v2.3.0.md
      - v2.2での変更点: guides/upgrade_to_v2.2.0.md
      - v2.1での変更点: guides/upgrade_to_v2.1.0.md
      - v2.0での変更点: guides/upgrade_to_v2.0.0.md
    - その他ガイド:
        - オブジェクトストレージ: guides/object_storage.md
  - 設定リファレンス:
    - プロバイダ設定: provider.md
    - プロバイダデータソース:
      - ゾーン: d/zone.md
    - コンピュート:
      - データソース:
        - 専有ホスト: d/private_host.md
        - サーバ: d/server.md
        - VNC接続情報: d/server_vnc_info.md
      - リソース:
        - 専有ホスト: r/private_host.md
        - サーバ: r/server.md
    - ストレージ:
      - データソース:
        - アーカイブ: d/archive.md
        - CD-ROM: d/cdrom.md
        - ディスク: d/disk.md
      - リソース:
        - アーカイブ: r/archive.md
        - アーカイブ共有: r/archive_share.md
        - CD-ROM: r/cdrom.md
        - ディスク: r/disk.md
    - ネットワーク:
      - データソース:
        - ブリッジ: d/bridge.md
        - スイッチ+ルータ: d/internet.md
        - ローカルルータ: d/local_router.md
        - パケットフィルタ: d/packet_filter.md
        - サブネット: d/subnet.md
        - スイッチ: d/switch.md
      - リソース:
        - ブリッジ: r/bridge.md
        - スイッチ+ルータ: r/internet.md
        - IPv4逆引き: r/ipv4_ptr.md
        - ローカルルータ: r/local_router.md
        - パケットフィルタ: r/packet_filter.md
        - パケットフィルタ(ルール): r/packet_filter_rules.md
        - サブネット: r/subnet.md
        - スイッチ: r/switch.md
    - アプライアンス:
      - データソース:
        - データベース: d/database.md
        - ロードバランサ: d/load_balancer.md
        - NFS: d/nfs.md
        - VPCルータ: d/vpc_router.md
      - リソース:
        - 自動バックアップ: r/auto_backup.md
        - データベース: r/database.md
        - データベース(リードレプリカ): r/database_read_replica.md
        - ロードバランサ: r/load_balancer.md
        - NFS: r/nfs.md
        - VPCルータ: r/vpc_router.md
    - グローバル:
      - データソース:
        - DNS: d/dns.md
        - GSLB: d/gslb.md
        - エンハンスドロードバランサ: d/proxylb.md
        - シンプル監視: d/simple_monitor.md
      - リソース:
        - DNS: r/dns.md
        - DNSレコード: r/dns_record.md
        - GSLB: r/gslb.md
        - エンハンスドロードバランサ: r/proxylb.md
        - エンハンスドロードバランサ(ACME設定): r/proxylb_acme.md
        - シンプル監視: r/simple_monitor.md
    - セキュアモバイル:
      - リソース:
        - モバイルゲートウェイ : r/mobile_gateway.md
        - SIM: r/sim.md
    - SMS:
      - データソース:
        - 2要素認証SMS: d/esme.md
      - リソース:
        - 2要素認証SMS: r/esme.md
    - Lab:
      - データソース:
        - マネージドPKI: d/certificate_authority.md
        - コンテナレジストリ: d/container_registry.md
        - エンハンスドデータベース: d/enhanced_db.md
      - リソース:
        - マネージドPKI: r/certificate_authority.md
        - コンテナレジストリ: r/container_registry.md
        - エンハンスドデータベース: r/enhanced_db.md
    - ウェブアクセラレータ:
        - データソース:
            - サイト情報: d/webaccel.md
        - リソース:
            - 証明書: r/webaccel_certificate.md
    - その他:
      - データソース:
        - アイコン: d/icon.md
        - スタートアップスクリプト: d/note.md
        - SSH公開鍵: d/ssh_key.md
      - リソース:
        - アイコン: r/icon.md
        - スタートアップスクリプト: r/note.md
        - SSH公開鍵: r/ssh_key.md
        - SSH公開鍵生成: r/ssh_key_gen.md
